language: node_js

node_js:
  - "8"

sudo: false

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

script: yarn test

services:
  - postgresql

before_script:
  - psql -c 'create database chlu_test;' -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
  firefox: 'latest'

env:
  global:
    - CHLU_POSTGRESQL_USER=postgres
    - PGPORT=5433